options:
  docker: true

pipelines:
  default:
    - step:
        name: Service testing and build
        image: golang:1.13
        script:
          - go mod download
          - go mod tidy
          - go test ./...
